function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('MP_Sum2_Tee_000', 'Black LD Organics Tee')
	AddTextEntry('MP_Sum2_Tee_001', 'White LD Organics Tee')
	AddTextEntry('MP_Sum2_Tat_000', 'Live Fast Mono')
	AddTextEntry('MP_Sum2_Tat_001', 'Live Fast Color')
	AddTextEntry('MP_Sum2_Tat_002', 'Cobra Biker')
	AddTextEntry('MP_Sum2_Tat_003', 'Bullet Mouth')
	AddTextEntry('MP_Sum2_Tat_004', 'Smoking Barrel')
	AddTextEntry('MP_Sum2_Tat_005', 'Concealed')
	AddTextEntry('MP_Sum2_Tat_006', 'Painted Micro SMG')
	AddTextEntry('MP_Sum2_Tat_007', 'Weapon King')
	AddTextEntry('MP_Sum2_Tat_008', 'Bigness Chimp')
	AddTextEntry('MP_Sum2_Tat_009', 'Up-N-Atomizer Design')
	AddTextEntry('MP_Sum2_Tat_010', 'Rocket Launcher Girl')
	AddTextEntry('MP_Sum2_Tat_011', 'Nothing Mini About It')
	AddTextEntry('MP_Sum2_Tat_012', 'Snake Revolver')
	AddTextEntry('MP_Sum2_Tat_013', 'Weapon Sleeve')
	AddTextEntry('MP_Sum2_Tat_014', 'Minimal SMG')
	AddTextEntry('MP_Sum2_Tat_015', 'Minimal Advanced Rifle')
	AddTextEntry('MP_Sum2_Tat_016', 'Minimal Sniper Rifle')
	AddTextEntry('MP_Sum2_Tat_017', 'Skull Grenade')
	AddTextEntry('MP_Sum2_Tat_018', 'Branched Skull')
	AddTextEntry('MP_Sum2_Tat_019', 'Scythed Corpse')
	AddTextEntry('MP_Sum2_Tat_020', 'Scythed Corpse & Reaper')
	AddTextEntry('MP_Sum2_Tat_021', 'Third Eye')
	AddTextEntry('MP_Sum2_Tat_022', 'Pierced Third Eye')
	AddTextEntry('MP_Sum2_Tat_023', 'Lip Drip')
	AddTextEntry('MP_Sum2_Tat_024', 'Skin Mask')
	AddTextEntry('MP_Sum2_Tat_025', 'Webbed Scythed')
	AddTextEntry('MP_Sum2_Tat_026', 'Oni Demon')
	AddTextEntry('MP_Sum2_Tat_027', 'Bat Wings')
	AddTextEntry('MP_Sum2_Tat_028', 'Laser Eyes Skull')
	AddTextEntry('MP_Sum2_Tat_029', 'Classic Vampire')
	AddTextEntry('MP_Sum2_Tat_030', 'Centipede')
	AddTextEntry('MP_Sum2_Tat_031', 'Flashy Eye')
	AddTextEntry('MP_Sum2_Tat_032', 'Many-eyed Goat')
	AddTextEntry('MP_Sum2_Tat_033', 'Three-eyed Demon')
	AddTextEntry('MP_Sum2_Tat_034', 'Smoldering Reaper')
	AddTextEntry('MP_Sum2_Tat_035', 'Sniff Sniff')
	AddTextEntry('MP_Sum2_Tat_036', 'Charm Pattern')
	AddTextEntry('MP_Sum2_Tat_037', 'Witch & Skull')
	AddTextEntry('MP_Sum2_Tat_038', 'Pumpkin Bug')
	AddTextEntry('MP_Sum2_Tat_039', 'Sinner')
	AddTextEntry('MP_Sum2_Tat_040', 'Carved Pumpkin')
	AddTextEntry('MP_Sum2_Tat_041', 'Branched Werewolf')
	AddTextEntry('MP_Sum2_Tat_042', 'Winged Skull')
	AddTextEntry('MP_Sum2_Tat_043', 'Cursed Saki')
	AddTextEntry('MP_Sum2_Tat_044', 'Smouldering Bat & Skull')
	AddTextEntry('MP_Sum2_Tat_045', 'Armored Arm')
	AddTextEntry('MP_Sum2_Tat_046', 'Demon Smile')
	AddTextEntry('MP_Sum2_Tat_047', 'Angel & Devil')
	AddTextEntry('MP_Sum2_Tat_048', 'Death Is Certain')
	AddTextEntry('MP_Sum2_Tat_049', 'Demon Drummer')
	AddTextEntry('MP_Sum2_Tat_050', 'Gold Gun')
	AddTextEntry('MP_Sum2_Tat_051', 'Blue Serpent')
	AddTextEntry('MP_Sum2_Tat_052', 'Night Demon')
	AddTextEntry('MP_Sum2_Tat_053', 'Mobster Skull')
	AddTextEntry('MP_Sum2_Tat_054', 'Wounded Head')
	AddTextEntry('MP_Sum2_Tat_055', 'Stabbed Skull')
	AddTextEntry('MP_Sum2_Tat_056', 'Tiger Blade')
	AddTextEntry('MP_Sum2_Tat_057', 'Gray Demon')
	AddTextEntry('MP_Sum2_Tat_058', 'Shrieking Dragon')
	AddTextEntry('MP_Sum2_Tat_059', 'Swords & City')
	AddTextEntry('MP_Sum2_Tat_060', 'Blaine County')
	AddTextEntry('MP_Sum2_Tat_061', 'Angry Possum')
	AddTextEntry('MP_Sum2_Tat_062', 'Floral Demon')
end)
